CREATE TABLE IF NOT EXISTS user_screenings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  full_name VARCHAR(191) NOT NULL,
  age INT UNSIGNED NOT NULL,
  gender TINYINT UNSIGNED NOT NULL,
  marital_status TINYINT UNSIGNED NOT NULL,
  has_children TINYINT(1) NOT NULL,
  education TINYINT UNSIGNED NOT NULL,
  education_other VARCHAR(191) NULL,
  hospital_id INT UNSIGNED NOT NULL,
  department_id INT UNSIGNED NOT NULL,
  current_position_years DECIMAL(5,2) NOT NULL,
  shift_work_years DECIMAL(5,2) NOT NULL,
  night_shift_per_month INT UNSIGNED NOT NULL,
  working_hours_per_week DECIMAL(5,2) NOT NULL,
  weight_kg DECIMAL(5,2) NOT NULL,
  height_cm DECIMAL(5,2) NOT NULL,
  has_underlying_disease TINYINT(1) NOT NULL,
  underlying_disease_detail TEXT NULL,
  phone VARCHAR(32) NOT NULL,
  line_id VARCHAR(191) NULL,
  inclusion_1 TINYINT(1) NOT NULL,
  inclusion_2 TINYINT(1) NOT NULL,
  inclusion_3 TINYINT(1) NOT NULL,
  inclusion_4 TINYINT(1) NOT NULL,
  inclusion_result TINYINT(1) NOT NULL,
  exclusion_1 TINYINT(1) NULL,
  exclusion_2 TINYINT(1) NULL,
  exclusion_3 TINYINT(1) NULL,
  exclusion_4 TINYINT(1) NULL,
  exclusion_result TINYINT(1) NOT NULL,
  screening_result TINYINT(1) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_screenings_user_id (user_id),
  CONSTRAINT fk_user_screenings_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
