CREATE TABLE IF NOT EXISTS sleep_diary_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_days TINYINT UNSIGNED NOT NULL DEFAULT 14,
  status ENUM('ACTIVE', 'COMPLETED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sleep_diary_active_user (user_id, status),
  KEY idx_sleep_diary_session_user (user_id),
  CONSTRAINT fk_sleep_diary_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sleep_diary_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  day_number TINYINT UNSIGNED NOT NULL,
  week_number TINYINT UNSIGNED NOT NULL,
  wake_date DATE NOT NULL,
  shift_type ENUM('MORNING', 'AFTERNOON', 'NIGHT', 'OFF') NOT NULL,
  bedtime TIME NOT NULL,
  attempt_sleep_time TIME NOT NULL,
  sol_minutes INT UNSIGNED NOT NULL,
  number_of_awakenings INT UNSIGNED NOT NULL DEFAULT 0,
  waso_minutes INT UNSIGNED NOT NULL,
  final_wake_time TIME NOT NULL,
  get_up_time TIME NOT NULL,
  sleep_after_final_wake_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  early_wake TINYINT(1) NOT NULL,
  tib_minutes INT UNSIGNED NOT NULL,
  tst_minutes INT UNSIGNED NOT NULL,
  sleep_efficiency DECIMAL(5,2) NULL,
  sleep_quality TINYINT UNSIGNED NOT NULL,
  morning_refreshment TINYINT UNSIGNED NOT NULL,
  shift_sleepiness TINYINT UNSIGNED NOT NULL,
  work_stress TINYINT UNSIGNED NOT NULL,
  nap TINYINT(1) NOT NULL,
  nap_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  caffeine_cups INT UNSIGNED NOT NULL DEFAULT 0,
  phone_before_bed_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  breathing_478 TINYINT(1) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sleep_diary_record_day (session_id, day_number),
  KEY idx_sleep_diary_records_user (user_id),
  CONSTRAINT fk_sleep_diary_records_session FOREIGN KEY (session_id) REFERENCES sleep_diary_sessions(id),
  CONSTRAINT fk_sleep_diary_records_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;